### ISSUE TITLE
Can scanpointgenerator be used to generate pmac PVT?

### ISSUE THREAD

**Issue by ulrikpedersen** [dls-controls/scanpointgenerator#50]
From the ICALEPCS2017 meeting I've had the question as to whether the scanpointgenerator can be used somehow to generate an ASCII PVT output to be loaded directly into a PMAC (possibly via the new pmac driver). I think the answer is no as it appears to produce JSON output... Would it be difficult to write a small demo that uses scanpointgenerator to create a PMAC PVT as a demo? Or is that a ridiculous idea?

**Comment by thomascobb** [comment]
This is really Malcolm's job. It may be possible to write a demo that is a cut down version of this, but for what purpose?

**Comment by ulrikpedersen** [comment]
> This is really Malcolm's job. It may be possible to write a demo that is a cut down version of this, but for what purpose?

Pretty old ticket... I can't remember who asked about this - perhpas NSLS-II? The idea was just as written in the ticket: to use scanpoint generator to generate a PVT scan that someone with a basic PMAC setup (i.e. without malcolm) can load straight onto the controller and run.

**Comment by gilesknap** [comment]
I have created https://jira.diamond.ac.uk/browse/BC-1103 to track progress on developing an example pmac Spline program.

**Comment by ulrikpedersen** [comment]
I've had no further queries regarding this from ICALEPCS2019. We may perhaps have missed an opportunity but it's hard to say.
Closing ticket without further action.
